from enum import IntEnum, auto

TURN_RADIUS = 190.0
WP_SPACING = TURN_RADIUS/2.5
TOLERANCE_MM = 30.0
VELOCITY_MM_S = 200.0
MAX_ACCEL_MM_S2 = 180.0
MAX_DECEL_MM_S2 = 180.0
MAX_ANGULAR_ACCEL_DEG_S2 = 180.0
MAX_ANGULAR_DECEL_DEG_S2 = 180.0
LOOKAHEAD_MM = WP_SPACING*1.25
ADVANCE_RADIUS_MM = WP_SPACING*1.25
APPROACH_VEL_MM_S = 50.0 # TODO: Tune (MED)

# LAPF
VELOCITY_LAPF = 180.0
ANGULAR_RAD_S_LAPF = 1.0
TOLERANCE_LAPF = 65.0
REPULSION_RANGE_LAPF = 190.0
REPULSION_GAIN_LAPF = 200.0
ATTRACTION_GAIN_LAPF = 1.0
FORCE_EMA_ALPHA_LAPF = 0.35
INFLATION_MARGIN_LAPF = 150.0
LEASH_LENGTH_LAPF = 250.0
LEASH_HALF_ANGLE_DEG_LAPF = 30.0
WP_SPACING_LAPF = 800.0
LOOKAHEAD_LAPF = 150.0
ADVANCE_RADIUS_LAPF = WP_SPACING_LAPF*0.4

SLAM_POSITION_FUSION_ALPHA = 0.2
SLAM_ORIENTATION_FUSION_ALPHA = 0.3

class HomeStage(IntEnum):
    HOME = auto()
    INIT = auto()

class NavStage(IntEnum):
    START_HEADING = auto()
    POSITION = auto()
    HEADING = auto()

class ManipStage(IntEnum):
    LEVEL = auto()
    OPEN = auto()
    CLOSE = auto()
    FORWARD = auto()
    RETREAT = auto()
    RAISE = auto()
    LOWER = auto()

PICK_SEQUENCE = [
    ManipStage.LEVEL,
    ManipStage.FORWARD,
    ManipStage.OPEN,
    ManipStage.LOWER,
    ManipStage.CLOSE,
    ManipStage.RAISE,
    ManipStage.RETREAT
]

PLACE_SEQUENCE = [
    ManipStage.LEVEL,
    ManipStage.FORWARD,
    ManipStage.LOWER,
    ManipStage.OPEN,
    ManipStage.RAISE,
    ManipStage.RETREAT
]